### ISSUE TITLE
Add support for hostname verification

### ISSUE THREAD

**Issue by jming422** [michaelklishin/langohr#100]
The RabbitMQ Java client provides the option for enabling hostname verification on connections using SSL/TLS by calling `enableHostnameVerification` on the `ConnectionFactory` after calling `useSslProtocol`. Currently hostname verification doesn't seem to be available using Langohr.

It would be great if `langohr.core/connect` could take another setting like `:verify-hostname`, which, if non-nil, would add `(.enableHostnameVerification)` to langhor.core/create-connection-factory here: https://github.com/michaelklishin/langohr/blob/39e2627c9516da8cdf14b60e42b8253756bcc7f4/src/clojure/langohr/core.clj#L335

**Comment by michaelklishin** [comment]
Contributions are welcome.

**Comment by michaelklishin** [comment]
@jming422 please take a look at master (e.g. the `tls-test` suite).
