### ISSUE TITLE
Arity error

### ISSUE THREAD

**Issue by borkdude** [michaelklishin/langohr#101]
This looks like an arity error:

https://github.com/michaelklishin/langohr/blob/39e2627c9516da8cdf14b60e42b8253756bcc7f4/src/clojure/langohr/http.clj#L166

Found with [clj-kondo](https://github.com/borkdude/clj-kondo)

**Comment by michaelklishin** [comment]
Thank you, this seem legit.

**Comment by michaelklishin** [comment]
Oh, and I love the name of your linter. Will definitely adopt :)
