### ISSUE TITLE
Allow customizing client-properties?

### ISSUE THREAD

**Issue by glenjamin** [michaelklishin/langohr#105]
When running a server with a lot of connections from various clients and services, it can be very useful to add additional identifying information to the client-properties. This then shows up in RabbitMQ admin.

The current client-properties are hard-coded:
https://github.com/michaelklishin/langohr/blob/master/src/clojure/langohr/core.clj#L307-L313

Would you accept a PR that made them customizable?

**Comment by michaelklishin** [comment]
Sure. Please note that connection name is a dedicated property for such cases and other clients, including the Java one used internally by Langohr, usually have a dedicated function for setting just that.

Thank you for considering  a contribution!

**Comment by glenjamin** [comment]
Oh thanks - I'll look into that.

In my testing so far it seems that product, platform and version are the ones that appear on the RabbitMQ admin UI's connection list - which makes them the most useful ones to override IMO

**Comment by glenjamin** [comment]
From the RabbitMQ 3.6.5 release notes:

https://rabbitmq.docs.pivotal.io/36/relnotes/release-notes-rabbitmq3.6.5.html

> **Management Plugin** Clients now can provide a human-readable connection name that will be displayed in the management UI. Currently Java, .NET and Erlang clients support this. In order to use this feature, set the connection_name key in client properties. Note that this name doesn’t have to be unique and cannot be used as a connection identifier, for example, in HTTP API requests.

**Comment by michaelklishin** [comment]
I shall respectfully disagree. At least product name and version can be used for your own app
but that’s also why we support connection_name, which will be displayed in management UI
and included into connection lifecycle log entries  if you actually set it.

I don’t think you want to override platform which is meant to be the OS.

My point was that together with a way to override any properties — something that most clients allow for — we should also add a dedicated setter for just connection name.

**Comment by glenjamin** [comment]
Sorry yes - that's what I took away from your previous message.

My comment about connection name was for reference - as I hadn't heard of it before (last time I worked on a RabbitMQ client it didn't exist yet).
