### ISSUE TITLE
New version coming soon?

### ISSUE THREAD

**Issue by vincentjames501** [michaelklishin/langohr#112]
Thanks for the recent dependency bumps @michaelklishin ! Any plans in the near future on releasing a new version with the updates? It just so happens we're updating a bunch of deps internally and would rather just bump our dep on langohr vs add some exclusions and overrides to all of our projects.

Love the library BTW!

**Comment by michaelklishin** [comment]
Should be realistic to ship one by Monday although I haven't published a Clojars release in a while and the process might have changed.

**Comment by michaelklishin** [comment]
[Done](https://clojars.org/com.novemberain/langohr)
