### ISSUE TITLE
Consider requiring Java9 minimum (ideally 11)

### ISSUE THREAD

**Issue by jimpil** [michaelklishin/langohr#118]
This would open the door to migrating away from `clj-http`, and instead rely on the native `HttpClient` (e.g. via [hato](https://github.com/gnarroway/hato) which is a great little library). 

Moreover, even if you don't like the sounds of that, the current `http` namespace could really use some love. 

First of all, I am kind of confused by the use of many dynamic vars (are these intended to be re-bound often?), and a bunch of `alter-var-root` calls under `connect!`. I am probably missing something, but I 'm having trouble understanding the motivation behind this kind of pattern.  From what I saw in various examples/tests etc, usages of `connect!` could easily be served by an atom instead. Anyway, it's just something that caught my eye...  

Secondly, the way `clj-http` is used, it creates a brand new `HttpClient` for every single outbound request (some functions do two requests, so that would be 2 `HttpClient` objects). This is kind of wasteful, and if fact the clj-http docs do draw attention to that. 

Anyway, I'm just probing here...let me know of your thoughts :+1:

**Comment by michaelklishin** [comment]
I am all for requiring Java 11. Please submit a PR. We will likely bump the version to 6.0 after merging it, and should ship `5.5.0` before doing so.

**Comment by michaelklishin** [comment]
Addressed in #119.
