### ISSUE TITLE
Add ability to register MetricsCollector/ObservationCollector

### ISSUE THREAD

**Issue by vincentjames501** [michaelklishin/langohr#121]
We'd like to use tools like micrometer to instrument the rabbitmq client. Looks like there are quite a few missing settings that can be supplied to the RabbitMQ client's `ConnectionFactory`

**Comment by vincentjames501** [comment]
@michaelklishin , thanks for the quick review. Any thoughts on a 5.5.0 release?

**Comment by michaelklishin** [comment]
I will publish it in the next couple of days.
