### ISSUE TITLE
Basic get (pulling API) always sends acks

### ISSUE THREAD

**Issue by boechat107** [michaelklishin/langohr#72]
I tried to use `langohr.basic/get` with explicit ack, but it seems to not work as expected. Acks are sent anyway.

I looked for a test of the function and I found this [code](https://github.com/michaelklishin/langohr/blob/0bb324c2ef2670e183978edd75a1a8177a66ef8c/test/langohr/test/basic_test.clj#L140), but I didn't understand its idea. Shouldn't it send some explicit ack?

**Comment by michaelklishin** [comment]
Your understanding is right, looks like an incorrect test and a possible bug.

**Comment by michaelklishin** [comment]
I can't reproduce this in the REPL and modifying [this test](https://github.com/michaelklishin/langohr/blob/master/test/langohr/test/basic_test.clj#L140) to use automatic acknowledgements makes it fail as expected. The test now sends a `basic.ack`, this is a decent quick fix for it.
