### ISSUE TITLE
documentation incorrect for http://reference.clojurerabbitmq.info/langohr.basic.html#var-publish

### ISSUE THREAD

**Issue by shmish111** [michaelklishin/langohr#79]
`publish` does not use varagrs for properties however example in docs show that it does.

**Comment by michaelklishin** [comment]
@shmish111 I don't see any examples [in master](https://github.com/michaelklishin/langohr/blob/master/src/clojure/langohr/basic.clj#L54), possibly we haven't redeployed API reference docs in a while.

**Comment by shmish111** [comment]
Also just found another one. Docs for `publish` says "Payload can be anything the langohr.conversion/BytePayload protocol is extended for" however the protocol is actually `clojurewerkz.support.bytes/ByteSource`

**Comment by michaelklishin** [comment]
@shmish111 OK, should be [good now](http://reference.clojurerabbitmq.info/langohr.basic.html), thanks for bringing this up.
