### ISSUE TITLE
Channel recovery exception fn arity

### ISSUE THREAD

**Issue by trptcolin** [michaelklishin/langohr#80]
Should `handle-channel-recovery-exception-fn` take 2 arguments here? https://github.com/michaelklishin/langohr/blob/eb0ae43324a7556695c9640aa7cf178fe9765768/src/clojure/langohr/core.clj#L267

Not urgent for me at all; just happened to notice when looking for something else.

**Comment by michaelklishin** [comment]
@trptcolin oops, you are right.
