### ISSUE TITLE
Channel Thread Safety

### ISSUE THREAD

**Issue by yuanbohan** [michaelklishin/langohr#81]
hi support,

in https://www.rabbitmq.com/api-guide.html Channels and Concurrency Considerations (Thread Safety)， it says: **Channel instances must not be shared between threads**.  

but in http://clojurerabbitmq.info/articles/queues.html  code samples,  `start-acking-consumer` and `start-skipping-consumer`, multi threads use the same channel.

This issue is to ensure if the code sample is ok, or if it isn't, will you update sample codes?

**Comment by michaelklishin** [comment]
This project does not use issues for support. Use the mailing list.

Consuming concurrently on a shared channel is fine. Publishing and performing synchronous operations (e.g. `queue.declare`) is not.
