### ISSUE TITLE
Redelivery backoff of rejected requeued messages

### ISSUE THREAD

**Issue by johanhaleby** [michaelklishin/langohr#83]
First of all thanks for a great library. 

I have a simple service that subscribes to messages from RabbitMQ and writes them down to a datastore. Sometimes this datastore is unavailable for some short periods of time (sometimes seconds but sometimes minutes). If this happens we do a basic.reject on the failed message with requeue set to true. While this works the message seems to get redelivered immediately. I'd like langohr to gracefully backoff the redelivery. For example first try to redeliver "immediately" then after 2, 3, 5, 8, 13 seconds etc. You can do this in [Spring AMQP](http://docs.spring.io/spring-amqp/reference/htmlsingle/) for example by different `recoveryBackOff` strategies such as `ExponentialBackOff` and `FixedBackOff` and this is what I miss the most (and virtually every time) I use langohr.

This is essentially a feature request for my question on [stackoverflow](http://stackoverflow.com/questions/34564405/rabbitmq-redelivery-backoff-of-rejected-requeued-messages).

**Comment by michaelklishin** [comment]
Langohr differs vastly in scope compared to Spring AMQP. It's a client library, not an opinionated application-centric framework. I'm not convinced features like this belong in client libraries.
