### ISSUE TITLE
Unable to compile the Project - langohr

### ISSUE THREAD

**Issue by MohamedHz** [michaelklishin/langohr#84]
Hi,

I am trying to compile the project but facing an error while compiling. For your reference the error is below:

[root@riemann langohr]# lein uberjar
Compiling 17 source files to /home/langohr/target/classes
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/langohr/src/java/com/novemberain/langohr/Connection.java:31: error: com.novemberain.langohr.Connection is not abstract and does not override abstract method getClientProvidedName() in com.rabbitmq.client.Connection
public class Connection implements com.rabbitmq.client.Connection, Recoverable {
       ^
1 error
1 warning
Compilation of Java sources(lein javac) failed.

Thank you in advance.

**Comment by michaelklishin** [comment]
`com.rabbitmq.client.Connection` needs to proxy `getClientProvidedName` which is a newly added method.

**Comment by MohamedHz** [comment]
Thanks It was working fine
