### ISSUE TITLE
Upgrade to RabbitMQ Java client 4.0

### ISSUE THREAD

**Issue by michaelklishin** [michaelklishin/langohr#86]
It's not just a trivial dependency bump: running `lein test` after doing that results in obscure connection constructor failures ("init failures").

**Comment by acogoluegnes** [comment]
A few new methods have been added to the `Connection`, `Channel`, and `RecoveryListener` interfaces in RabbitMQ Java Client 4.0. It's the cause of at least some of the errors in the test suite after the upgrade.

The modifications below fix a few errors (just pointing out the location, the fixes could do more harm than good considering my skills in Clojure).

https://github.com/michaelklishin/langohr/blob/master/src/java/com/novemberain/langohr/Connection.java#L119
```java
  public void onRecovery(final IFn f) {
    if (this.automaticRecoveryEnabled()) {
      ((AutorecoveringConnection) this.delegate).addRecoveryListener(new RecoveryListener() {
        public void handleRecovery(com.rabbitmq.client.Recoverable recoverable) {
          f.invoke(recoverable);
        }

        @Override
        public void handleRecoveryStarted(Recoverable recoverable) {

        }
      });
    }
  }
```

https://github.com/michaelklishin/langohr/blob/master/src/java/com/novemberain/langohr/Connection.java#L400
```java
  @Override
  public void setId(String id) {
    delegate.setId(id);
  }

  @Override
  public String getId() {
    return delegate.getId();
  }
```
https://github.com/michaelklishin/langohr/blob/master/src/clojure/langohr/core.clj#L197
```clojure
(defn on-recovery
  "Registers a network recovery callback on a (Langohr) connection or channel"
  [^Recoverable target ^IFn callback]
  (.addRecoveryListener target (reify RecoveryListener
                                 (^void handleRecovery [this ^Recoverable it]
                                   (callback it))
                                 (^void handleRecoveryStarted [this ^Recoverable it]
                                   (callback it))
                                 )))
```

**Comment by michaelklishin** [comment]
You don't want to call the same function for `handleRecovery` and `handleRecoveryStarted`. We should introduce another arity that accepts another argument which is a `handle-recovery-started` function and for the one we have, pass `handleRecoveryStarted ` a no-op.

**Comment by michaelklishin** [comment]
Thanks @acogoluegnes, `RecoveryListener`-related changes were it.
