### ISSUE TITLE
Reconnecting to a cluster of RabbitMQ

### ISSUE THREAD

**Issue by dupuchba** [michaelklishin/langohr#90]
Hello all,

First thx for this amazing lib, it’s helping a lot !
I am still struggling for 1 problem (see below)
***
> Context : I am setting up a simple RabbitMQ cluster with a direct   exchange behind an HAProxy. Everything is working great but **I can’t figure out how my consumer can automatically reconnect to the cluster when there is a failure** 

If someone has some clue it would be great

Thx !

**Comment by michaelklishin** [comment]
Questions belong to mailing lists (either Langohr or rabbitmq-users).

**Comment by michaelklishin** [comment]
When a node fails, HAproxy will detect it and close client's TCP connection. Client then has to reconnect, after which HAproxy will route the connection to a different node.

**Comment by dupuchba** [comment]
thx :-) - I guess it means that I have to `(try ... catch)` all the code for when it fails and then reconnects when it does ?

**Comment by michaelklishin** [comment]
[Read the docs](http://clojurerabbitmq.info/articles/error_handling.html).

**Comment by dupuchba** [comment]
thx for your time @michaelklishin
