### ISSUE TITLE
Troubleshooting guide down

### ISSUE THREAD

**Issue by dupuchba** [michaelklishin/langohr#91]
This page is down => 
http://clojurerabbitmq.info/articles/troubleshooting.html
(was not yersterday)

**Comment by michaelklishin** [comment]
It was [never written and listed as TBD on the index page](http://clojurerabbitmq.info/articles/guides.html).

The guide you were referred to in #90 is a different one.

**Comment by michaelklishin** [comment]
I have previously asked (in #90) that questions are posted to the mailing list. I'd highly appreciate if only specific, researched, actionable items or ideas are posted as GitHub issues. This is not a support forum (for the projects I maintain).

**Comment by dupuchba** [comment]
Ok, I thought it was the right place for a 404 on the docs
