### ISSUE TITLE
Log warning

### ISSUE THREAD

**Issue by r-custodio** [michaelklishin/langohr#95]
I'm not using log at my project, but everytime when I start it gives me a warning about slf4j, I'm trying to find it but unfortunately with no success

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Someone can help me out?

PS: This does not happen at 3.7.0 version

**Comment by r-custodio** [comment]
Anything?

**Comment by michaelklishin** [comment]
RabbitMQ Java client does not have a [SLF4J](https://www.slf4j.org) implementation on class path and thus results to a no-op implementation. Java client versions prior to 4.0 did not use SLF4J (which is an industry standard common logging interface in the Java ecosystem).

**Comment by michaelklishin** [comment]
Just noticed that SLF4J mentions this exact warning [on their main doc manual page](https://www.slf4j.org/manual.html).

**Comment by r-custodio** [comment]
Thanks @michaelklishin
